# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.my variable }}.

title: EasyZD
email: jionjion@aliyun.com
repository: jionjion/jionjion.github.io
description: >- # this means to ignore newlines until "baseurl:"
  一款简单的 Chrome 扩展插件，可以进行简单的中、英文翻译，支持屏幕划词翻译哦~(๑¯◡¯๑)

github_username: jionjion


# if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
domain: jionjion.github.io
# the base hostname and protocol for your site, e.g. http://example.com
url: https://jionjion.github.io/
# place folder name if the site is served in a sub folder
baseurl: /EasyZD/

# Build settings
theme: minima #jekyll-theme-cayman
# remote_theme: pages-themes/cayman

plugins:
  - jekyll-spaceship

# minima home page
header_pages:

# minima date
minima:
  date_format: "%b %-d, %Y"
page:
  list_title: 更多..

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
